### ISSUE TITLE
Capitalized mnemonics and registers are not stylized 

### ISSUE THREAD

**Issue by wordandahalf** [SWW13/language-x86asm#11]
![screenshot](https://cloud.githubusercontent.com/assets/10679776/20854289/281643de-b8b8-11e6-9426-bf4c9596768e.png)

Pretty simple - capitalized mnemonics and registers are not stylized.

**Comment by wordandahalf** [comment]
Also, it seems that the .inc extension for files for including assembly code is not a valid file type.

**Comment by SWW13** [comment]
Both changes are in the v0.9.0 release.

**Comment by wordandahalf** [comment]
Thanks!
